Adjust error wording when loading missing files
```shell
$ SSL_CERT_FILE="notexist" target/debug/examples/google
thread 'main' panicked at examples/google.rs:7:58:
could not load platform certs: Custom { kind: NotFound, error: "could not load certs from dir notexist: No such file or directory (os error 2)" }
```

Note "from dir notexist".  In this case `path.is_file()` is false
(because it doesn't exist) but that doesn't imply it was being
read as a directory.